---
sudo: false
language: python
python:
  - 3.6
install:
  - cp backend/config.example.py backend/config.py
  - pip install tox-travis
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt  # required for building the docs
services:
  - redis-server
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c "CREATE DATABASE flask_test;" -U postgres
  - psql -c "CREATE USER flask_test WITH PASSWORD 'flask_test';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE flask_test TO flask_test;" -U postgres
script:
  - tox
  - travis-sphinx build --nowarn --source=docs
after_success:
  - travis-sphinx deploy
