---
sshd_config_mode: '0644'
sshd_packages:
  - openssh
  - openssh-server
sshd_sftp_server: /usr/libexec/openssh/sftp-server
sshd:
  SyslogFacility: AUTHPRIV
  PermitRootLogin: forced-commands-only
  AuthorizedKeysFile: .ssh/authorized_keys
  PasswordAuthentication: no
  ChallengeResponseAuthentication: no
  UsePAM: yes
  X11Forwarding: yes
  PrintLastLog: yes
  UsePrivilegeSeparation: sandbox
  AcceptEnv:
    - LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
    - LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
    - LC_IDENTIFICATION LC_ALL LANGUAGE
    - XMODIFIERS
  Subsystem: "sftp {{ sshd_sftp_server }}"
sshd_os_supported: yes
